### ISSUE TITLE
agregar salida formato PDF

### ISSUE THREAD

**Issue by jorgepz** [ONSAS/ONSAS.docs#29]
tal vez usando https://github.com/JuliaDocs/DocumenterLaTeX.jl ?

**Comment by mforets** [comment]
si. hay que cambiar el make.jl.  lo menciona aca: https://juliadocs.github.io/Documenter.jl/dev/man/other-formats/#PDF-Output-via-LaTeX

**Comment by jorgepz** [comment]
* [ ] hacer funcionar con format LaTeX
* [ ] agregar flag para definir si salida es HTML o PDF
* [ ]  hacer que travis use el output HTML

**Comment by JoaquinViera** [comment]
Dejo este link: Aquí parecería estar la solución para las figuras pdf_tex

https://discourse.julialang.org/t/create-pdf-document-with-pgfplotsx-figures-captions-a-table-and-some-text/26478

**Comment by jorgepz** [comment]
cierro por estar ahora en onsas.m
