### ISSUE TITLE
Ver de agregar editores de texto a la wiki

### ISSUE THREAD

**Issue by JoaquinViera** [ONSAS/ONSAS.docs#46]

**Comment by jorgepz** [comment]
tal vez acá podemos ir poniendo los que usamos y cuando hayan 2 o 3 cerramos el issue.

yo agregué a la wiki el ReText que uso en linux. supongo debe haber alguno similar en windows/mac. me parece que los propios entornos como atom o jupyterlab también permiten editar...

**Comment by jorgepz** [comment]
no lo pondría para onsas.m
