### ISSUE TITLE
Documentar parámetros de arc length

### ISSUE THREAD

**Issue by JoaquinViera** [ONSAS/ONSAS.docs#70]
Al modelar con arc Length se piden estos parámetros pero no se encuentra documentado como ingresarlos
analysisSettings.posVariableLoadBC
analysisSettings.iniDeltaLamb

**Comment by jorgepz** [comment]
bien de bien, trato de mirarlo, gracias!

**Comment by jorgepz** [comment]
lo cierro por haber abierto el otro
