### ISSUE TITLE
Cita a ONSAS

### ISSUE THREAD

**Issue by JoaquinViera** [ONSAS/ONSAS.docs#71]
Podría estar bueno incluir en la documentación o en la página de presentación del ONSAS.m cómo citar el código

**Comment by jorgepz** [comment]
Gran idea!  Tengo en mente mover la documentación al mismo repo del código onsas.m y ahi agregamos al repo .m how to cite... Si querés generate este issue en el repo de onsas.m!

**Comment by jorgepz** [comment]
lo cierro por estar abierto https://github.com/ONSAS/ONSAS.m/issues/337
